.DEFAULT_GOAL := bech

clean:
	cargo clean

fmt:
	cargo-fmt --all

check:
	cargo check --all-features

bech:
	cargo bench

test:
	cargo test

100th:
	cargo run --example print_100th_fib

cycle:
	cargo run --example cycle

step_by:
	cargo run --example step_by
