# https://github.com/rust-lang/rustfmt/blob/master/Configurations.md
# and: https://rust-lang.github.io/rustfmt/

array_width = 60
attr_fn_like_width = 70

## only available in nightly channel
# binop_separator = "Front"
# blank_lines_lower_bound = 0
# blank_lines_upper_bound = 1
# brace_style = "SameLineWhere"

chain_width = 60

## only available in nightly channel
# color = "Auto"
# combine_control_expr = true
# comment_width = 80
# condense_wildcard_suffixes = false
# control_brace_style = "AlwaysSameLine"

disable_all_formatting = false
edition = "2021"

## only available in nightly channel
# empty_item_single_line = true
# enum_discrim_align_threshold = 0
# error_on_line_overflow = false
# error_on_unformatted = false

fn_args_layout = "Tall" # This option is deprecated and has been renamed to fn_params_layout
fn_call_width = 60

## unknown configuration option
#fn_params_layout = "Tall"

## only available in nightly channel
# fn_single_line = false

force_explicit_abi = true

## only available in nightly channel
# force_multiline_blocks = false
# format_code_in_doc_comments = true
# doc_comment_code_block_width = 100
# format_generated_files = false
# format_macro_matchers = true
# format_macro_bodies = true
#skip_macro_invocations = [] # Unknown configuration option
# format_strings = true

hard_tabs = false

## only available in nightly channel
# hex_literal_case = "Preserve"
# hide_parse_errors = false
# ignore = []
# imports_indent = "Block"
# imports_layout = "HorizontalVertical"
# indent_style = "Block"
# inline_attribute_width = 0
# match_arm_blocks = true

match_arm_leading_pipes = "Never"
match_block_trailing_comma = false
max_width = 100
merge_derives = true

## only available in nightly channel
# imports_granularity = "Crate"

newline_style = "Unix"

## only available in nightly channel
# normalize_comments = true
# normalize_doc_attributes = true
# overflow_delimited_expr = true

remove_nested_parens = true

## only available in nightly channel
# reorder_impl_items = true

reorder_imports = true

## only available in nightly channel
# group_imports = "StdExternalCrate"

reorder_modules = true

## only available in nightly channel
# required_version = "1.5.1"

short_array_element_width_threshold = 10

## only available in nightly channel
# skip_children = false

single_line_if_else_max_width = 50

## only available in nightly channel
# space_after_colon = true
# space_before_colon = false
# spaces_around_ranges = false
# struct_field_align_threshold = 0
# struct_lit_single_line = true

struct_lit_width = 18
struct_variant_width = 35
tab_spaces = 4

## only available in nightly channel
# trailing_comma = "Vertical"
# trailing_semicolon = true
# type_punctuation_density = "Wide"
# unstable_features = false

use_field_init_shorthand = true
use_small_heuristics = "Default"

#>= 2.0.0
#width_heuristics = "Scaled"

use_try_shorthand = true

## only available in nightly channel
# version = "Two"
# where_single_line = false
# wrap_comments = true
